- hosts: 192.168.1.8
  vars_files:
          - vars.yml
  tasks:
          - file: 
                state: directory
                path: "/dvd"
          - mount: 
                src: "/dev/cdrom"
                path: "/dvd"
                state: mounted
                fstype: "iso9660"
          - yum_repository: 
                baseurl: "/dvd/AppStream"
                name: "dvd1"
                description: "my yum dvd for package"
                gpgcheck: no

          - yum_repository: 
                baseurl: "/dvd/BaseOS"
                name: "dvd2"
                description: "my yum dvd for package"
                gpgcheck: no
          - package: 
                name: httpd
                state: present
            notify: restart httpd
          - file:
                state: directory
                path: "/var/www/{{DR}}"
          - name: "template"          
            template:
                dest: "/etc/httpd/conf.d/lw.conf"
                src: "httpd.conf"
            notify: restart httpd
          - copy: 
                dest: "/var/www/{{DR}}/nikki.html"
                content: "hello i am nikhil helllo jeeeeeeeee\n "
          - firewalld:
                port: "{{port1}}/tcp"
                state: enabled
                permanent: yes
                immediate: yes
  handlers: 
          - name : restart httpd  
            service :
                name: httpd
                state: restarted
                enabled: yes

